---
ansible_connection: amazon.aws.aws_ssm

ansible_aws_ssm_region: us-east-1

ansible_aws_ssm_bucket_name: >-
  eks-kubernetes-cicd-ansible-transport-421438965568-us-east-1

ansible_aws_ssm_bucket_sse_mode: AES256

ansible_python_interpreter: /usr/bin/python3

kubectl_version: "1.35.3"
kubectl_release_date: "2026-04-08"

helm_version: "v3.21.3"

trivy_version: "0.74.0"

checkov_version: "3.3.8"