---
ansible_connection: amazon.aws.aws_ssm

ansible_aws_ssm_region: us-east-1

ansible_aws_ssm_bucket_name: >-
  eks-kubernetes-cicd-ansible-transport-421438965568-us-east-1

ansible_aws_ssm_bucket_sse_mode: AES256

ansible_python_interpreter: /usr/bin/python3