apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: cicd-app
    app.kubernetes.io/instance: {{ .Release.Name }}
automountServiceAccountToken: false