apiVersion: rbac.authorization.k8s.io/v1
kind: Role

metadata:
  name: jenkins-deployer
  namespace: challenge-app

rules:

  # Helm-managed core resources
  - apiGroups:
      - ""
    resources:
      - services
      - serviceaccounts
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  # Deployment lifecycle
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  # Read rollout-created ReplicaSets
  - apiGroups:
      - apps
    resources:
      - replicasets
    verbs:
      - get
      - list
      - watch

  # HPA
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  # ALB Ingress
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  # Deployment verification
  - apiGroups:
      - ""
    resources:
      - pods
      - events
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  name: jenkins-deployer
  namespace: challenge-app

subjects:
  - kind: Group
    name: jenkins-deployers
    apiGroup: rbac.authorization.k8s.io

roleRef:
  kind: Role
  name: jenkins-deployer
  apiGroup: rbac.authorization.k8s.io