apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: cicd-app-gitops
  namespace: argocd

spec:
  project: default

  source:
    repoURL: git@github.com:uzobola/eks-kubernetes-cicd-platform.git
    targetRevision: gitops
    path: helm/cicd-app

    helm:
      releaseName: cicd-app

  destination:
    server: https://kubernetes.default.svc
    namespace: cicd-app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=false